CREATE TABLE [dbo].[WORKS_ON]
(
	[Essn] CHAR(9) NOT NULL , 
    [Pno] INT NOT NULL, 
    [Hours] DECIMAL(3, 1) NOT NULL, 
    PRIMARY KEY ([Pno], [Essn]), 
    CONSTRAINT [PK_WORKS_ON_EMPLOYEE] FOREIGN KEY ([Essn]) REFERENCES [EMPLOYEE]([Ssn]), 
    CONSTRAINT [PK_WORKS_ON_PROJECT] FOREIGN KEY ([Pno]) REFERENCES [PROJECT]([Pnumber])
)
